version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.11.1
    - 4.14.1
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.11.1
    - 4.14.1
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.2
    - 11.2.3
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.8
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.7
